cookie_array = []
wasted_cookie = []
ip = "127.0.0.1"
port = 8484
check_update = true
auto_update = false
no_fs = false
log_to_file = false
password = "rrDShEMSqDCwQgGWZ45EaPESUfhT9Hyb9wKEspbV5CE6xnvaNRxdPG5zsgGDpGmM"
admin_password = "EgwLrFJSHmbP6YRT3qryKDBHDfT2yxNJDndMZL89mypRJYcgpA4pPDTNYKuV5mkN"
max_retries = 5
preserve_chats = false
web_search = false
enable_web_count_tokens = false
sanitize_messages = false
skip_first_warning = false
skip_second_warning = false
skip_restricted = false
skip_non_pro = false
skip_rate_limit = true
skip_normal_pro = false
use_real_roles = true
custom_prompt = ""
